### ISSUE TITLE
[Firefox] Settings not retained after clearing cookies and/or offline website data 

### ISSUE THREAD

**Issue by Thomasc5** [cschiller/zhongwen#39] opened 2020-02-09 05:03 UTC
To reproduce:
1. Zhongwen options:  Set "display characters in a larger font size"
2. Firefox:  "Clear Recent History..."  (includes Cookies and/or Offline Website Data)
3. Zhongwen font size setting not retained

![Capture](https://user-images.githubusercontent.com/5540385/74096597-ea0b8a80-4b3b-11ea-9adc-7fa0c08d3c49.JPG)

p.s. The unofficial fork of zhongwen doesn't have this problem.

Thank you

**Comment by cschiller** [comment] 2020-02-09 21:57
I cannot confirm this. It works for me. Please test this again.

**Comment by cschiller** [comment] 2020-02-09 22:10
One more question: In your screenshot it looks like you're not clearing the offline website data, but the title of this issue suggests you're clearing the data. Of course, when you're clearing offline website data it won't keep your settings because you're clearing them! So my advice would be: If you want to keep your settings then don't clear them.

**Comment by Thomasc5** [comment] 2020-02-10 03:11
This is how I reproduce the problem:

1. Change some default settings: 
![A](https://user-images.githubusercontent.com/5540385/74117224-ef2b1100-4bf1-11ea-9d0d-033f9e322105.jpg)

2. Enable Zhongwen and it works as expected:
![B](https://user-images.githubusercontent.com/5540385/74117305-35807000-4bf2-11ea-9348-e76753e7b116.jpg)

3. Disable Zhongwen. Clear everything out in the browser before closing it. 
![C](https://user-images.githubusercontent.com/5540385/74117412-85f7cd80-4bf2-11ea-8875-ca872694907e.jpg)

4. Wait a few seconds. Launch browser. Go to the same page and enable Zhongwen. The settings would return to default:
![D](https://user-images.githubusercontent.com/5540385/74117537-f30b6300-4bf2-11ea-8c3e-eae2c85526a9.jpg)

p.s. If the above problem can't be reproduced, try clear the browser and relaunch it a few more times. 
p.p.s. I had tried the following test cases: 1. not clearing cookies; 2. not clearing offline website data; 3. not clearing both cookies and offline website data.  None of these seems to help keeping the settings.

Thank you so much.

**Comment by cschiller** [comment] 2020-02-10 09:11
It looks like you are clearing your offline web site data. This will clear the Zhongwen settings as well. So it works as expected.

**Comment by Thomasc5** [comment] 2020-02-11 06:35
I know nothing about programming. But shouldn't an extension settings be saved somewhere else that they won't get reset when users clear their browsing history? 

e.g. 
"Although this API is similar to Window.localStorage it is recommended that you don't use Window.localStorage in extension code. Firefox will clear data stored by extensions using the localStorage API in various scenarios where users clear their browsing history and data for privacy reasons, while data saved using the storage.local API will be correctly persisted in these scenarios."

[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local](url)

**Comment by cschiller** [comment] 2020-02-11 08:42
The problem is, Zhongwen for Chrome - which shares the same codebase with Zhongwen for Firefox -has been using the localStorage API for many years. At the time it was written, the storage.local API didn't even exist. If I were to change it now, then tens of thousands of users would lose their settings. If I were to start all over again, I would use the storage.local API, but making such a critical change that will affect such a large number of users in my opinion is not worth the trouble. I don't know how often you clear your offline website data, probably not on a daily basis. Even so, if the only problem for you is having to change the font size afterwards then I would hope this is acceptable to you.

**Comment by Thomasc5** [comment] 2020-02-14 03:58
The problem is even if I just clear the "cookies"  (i.e. leave the offline website data untouched), the settings would still be reset to default.  

![Capture](https://user-images.githubusercontent.com/5540385/74499329-4c8acf00-4f1e-11ea-908d-eba4ea7a831b.JPG)

Anyway, I understand the dilemma. I'll try figure out how to hardcode the large font size as the default.  

Thank you

**Comment by kondeeza** [comment] 2020-11-14 22:21
> 
> 
> The problem is even if I just clear the "cookies" (i.e. leave the offline website data untouched), the settings would still be reset to default.
> 
> ![Capture](https://user-images.githubusercontent.com/5540385/74499329-4c8acf00-4f1e-11ea-908d-eba4ea7a831b.JPG)
> 
> Anyway, I understand the dilemma. I'll try figure out how to hardcode the large font size as the default.
> 
> Thank you

If you're still having problem then I suggest checking out **Stylus extension** (Extension to modify any CSS on the fly). I do not know if user config is persistent after clearing offline website data though. Here's the CSS to increase Zhongwen Lookup Dict size btw

```
/* Chinese Lookup Dict - Zhongwen */
#zhongwen-window .w-hanzi-small,
#zhongwen-window .w-pinyin-small {
    font-size: 40px !important;
}

#zhongwen-window .w-def-small {
    font-size: 34px !important;
}
```

**Comment by cschiller** [comment] 2020-12-30 20:19
I tested it again with FF 84.0.1. Even when clearing everything (cookies, site preferences and offline website data), after a browser restart all my Zhongwen specific settings are retained.

I'm closing this since I cannot reproduce the problem.

**Closed by cschiller** 2020-12-30 20:19 UTC
Labels: cannot reproduce
